apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbctest4132
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbctest4132
    app.kubernetes.io/part-of: fbc-e2e-test
  name: fbctest4132
  namespace: user1-tenant
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app.kubernetes.io/instance: fbctest4132
status:
  loadBalancer: {}
