apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: 413-fbc-test
  namespace: user1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/scoheb/user-workload@sha256:6e04a0060fbbf56adc55e2a175a6761c5bff6e7a81db05e6edb59fe978dd51c8
        name: container-image
        resources: {}
status: {}
