apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc413
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc413
    app.kubernetes.io/part-of: fbc-e2e-test
  name: fbc413
  namespace: user1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: fbc413
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fbc413
    spec:
      containers:
      - image: quay.io/scoheb/user-workload@sha256:584ad37d410ff7faa05a8eafad9a63e1388a1e3aeca783df8e9ef3f8fb837b92
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 50051
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 50051
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
